notifications:
  email: false
language: C
sudo: required
branches:
  only:
    - master
script:
  - cd test && make build_and_run
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libcurl4-openssl-dev
